### ISSUE TITLE
feat: Extend API's types

### ISSUE THREAD

**Issue by ffMathy** [ftrackhq/ftrack-ts-schema-generator#11]
If we use [this feature](https://stackoverflow.com/questions/69590147/how-to-override-or-extend-interfaces-and-types-from-an-existing-library-in-types) to extend interfaces from another library, I think we could make it so that the `@ftrack/api` entity types would automatically reference generated schema types if possible.

Let's say we created a third package which just contained the `EntityTypeMap` type. That type would be entirely empty and would be published as a package called `@ftrack/schema`. This package would be reference both by `@ftrack/ts-schema-generator` and `@ftrack/api`.

In `@ftrack/api`, the interface could be extended with a default base key that represents untyped entities.

And then in `@ftrack/ts-schema-generator` we also extend the interface by instead emitting `.d.ts` files which then contain the types.

That would be insanely awesome. Then you would never need type-casts, even with types from the official API client!

As a bonus, we could define a union-type for all generated entities too, for cool type discrimination.

**Comment by gismya** [comment]
Was thinking since it was an unclosed question :) 

But yes, something similar sounds very much in line with what I'm thinking about. I'm taking some inspiration from the type extendability they are using in [material-ui](https://github.com/mui/material-ui)

**Comment by ffMathy** [comment]
Glad we're on the same page! This is going to be awesome! You guys rock! 😍

Didn't know MUI did something similar!

**Comment by ffMathy** [comment]
Wait, wow you're right. The link indeed doesn't have an answer. I swear there was one last time I looked 🤣

Maybe I should just go full into vacation mode and enjoy my vacation 😅 I think I'm bad at doing each thing half-focused 😅

**Comment by ffMathy** [comment]
@gismya can you share more about what your thoughts with this were? Then I'll get a PR started!

**Comment by ffMathy** [comment]
I tried my best over at this PR: https://github.com/ftrackhq/ftrack-javascript/pull/143

Let me know what you think!

**Comment by ffMathy** [comment]
I assume we can close this now?
