### ISSUE TITLE
Integration test instance?

### ISSUE THREAD

**Issue by ffMathy** [ftrackhq/ftrack-ts-schema-generator#24]
The contributions I do to Ftrack are often in my spare time (because I think the types of issues are fun, and I like contributing to Open Source in general), and often from my own computer, which can't reach the Ftrack cluster of my work.

This makes it particularly hard to make contributions that rely on very real output from Ftrack (for instance when generating types).

It'd be awesome if Ftrack put together an integration testing cluster that would be accessible from ftrack-ts-schema-generator and ftrack-javascript etc, but where the API key would be stored as a secret, and run in the repo as part of GitHub Actions.

And then, ideally (pretty please?) it'd be awesome if I could also get access to such an API key, so I could help contribute a lot more.

**Comment by ffMathy** [comment]
Actually...

What would be even better, is if someone could do a `query_schemas` query just once on a fresh new Ftrack instance, and then we could use that for the snapshot tests etc.

New fresh instances of Ftrack do have custom attributes etc, right?

**Comment by gismya** [comment]
There are defaults for almost everything, and very few are mandatory, so there's really no "bare minimum" to properly base a snapshot on. But a fresh instance is probably the best alternative. To access a ftrack instance for development, the easiest thing to do is sign up for a [trial account here](https://account.ftrack.com/try). If you need a more persistent one I can set you up with one.

**Comment by ffMathy** [comment]
But should we have a trial instance that is used from GitHub Actions too?

**Comment by gismya** [comment]
I'm not sure integration tests are needed, I think snapshot tests should be enough. Or do you have any test case that would greatly benefit from integration tests?

**Comment by gismya** [comment]
If you need it, I'll make sure to get you a license. Just send me a message and I'll arrange everything.
