### ISSUE TITLE
Naming conflicts

### ISSUE THREAD

**Issue by gismya** [ftrackhq/ftrack-ts-schema-generator#29]
The recent release has naming conflicts on the new hard-typed types where they conflict with the generic type descriptions for the types.

This goes for
'CustomAttributeConfiguration'.
'ObjectType'.
'ProjectSchema'.
'Type'.

@ffMathy, do you have a suggestion for naming for the new ones you would like, or should I come up with something?

**Comment by ffMathy** [comment]
I applied a fix for it actually, because I had some spare time. It's over at #30.
