### ISSUE TITLE
Timeout for custom attributes

### ISSUE THREAD

**Issue by ffMathy** [ftrackhq/ftrack-ts-schema-generator#31]
When I introduced the PR to add custom attributes, it does so using the following query:

```
select default, label, values, key, project_id, entity_type, is_hierarchical, object_type.name from CustomAttributeConfiguration order by sort
```

Apparently, when running towards our production or staging cluster, this query is too heavy, or takes too long time, resulting in a timeout.

Is there anything about this that should be expensive? I feel like fetching maybe roughly 200 custom attributes should be relatively simple.

**Comment by gismya** [comment]
The issue is the values, which searches for all the uses of the custom attribute in all the tasks. It's never actually used either, so should definitely be removed.
